//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Report
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual DateTime Time
	{
		get;
		set;
	}

	public virtual DateTime Date
	{
		get;
		set;
	}

	public virtual string Place
	{
		get;
		set;
	}

	public virtual int Observed_Id
	{
		get;
		set;
	}

	public virtual string Comment
	{
		get;
		set;
	}

	public virtual int Author_Id
	{
		get;
		set;
	}

	public virtual string Content
	{
		get;
		set;
	}

}

