//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ClientServerLib;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Database {
    public class PET {
        public static string connString = @"Data Source = CV - PC - T - 04\SQLEXPRESS; Initial Catalog = S3Eksamen; Integrated Security = True";

    }

}
