//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Entities;

namespace Database {
    public class InfoWrapper {
        public virtual Image GetImage(int id) {
            throw new System.NotImplementedException();
        }

        public virtual Address GetAddress(int id) {
            throw new System.NotImplementedException();
        }

        public virtual Appearance GetAppearence(int id) {
            throw new System.NotImplementedException();
        }

        public virtual void SaveAddress(Address address) {
            throw new System.NotImplementedException();
        }

        public virtual void SaveImage(Image image) {
            throw new System.NotImplementedException();
        }

        public virtual void SaveAppearence(Appearance appearance) {
            throw new System.NotImplementedException();
        }

    }

}
