//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Entities;
using Database;
using System.Data;

namespace Database {
    public class InformerWrapper {
        static Func<IDataRecord, Informer> infsel = CodeGen.GenObjectSelector<Informer>();

        public static List<Informer> GetAllInformers() {

            DBConnection db = new DBConnection(PET.connString);

            return db.ReadToList<Informer>("SelectAllInformers", infsel).ToList();


        }

        public static void SaveInformer(Informer informer) {
            throw new System.NotImplementedException();
        }

    }

}
