//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AgentWrapper
{
	public virtual List<Agent> GetAllAgents()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SaveAgent(Agent agent)
	{
		throw new System.NotImplementedException();
	}

}

