//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Appearance
{
	public virtual float Height
	{
		get;
		set;
	}

	public virtual string Eyecolor
	{
		get;
		set;
	}

	public virtual string Haircolor
	{
		get;
		set;
	}

	public virtual int Id
	{
		get;
		set;
	}

}

