//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InformerWrapper
{
	public virtual List<Informer> GetAllInformers()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SaveInformer(Informer informer)
	{
		throw new System.NotImplementedException();
	}

}

