//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Person
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string CPR
	{
		get;
		set;
	}

	public virtual string Nationality
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

}

