//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ReportWrapper
{
	public virtual List<Report> GetReports(int person_id)
	{
		throw new System.NotImplementedException();
	}

	public virtual List<Report_Log> GetReportLogs(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SaveReport(Report report)
	{
		throw new System.NotImplementedException();
	}

}

